FROM python:3.11

RUN apt-get update && \
    apt-get install -y gcc tshark nmap && \
    apt install -y docker.io && \
    rm -rf /var/lib/apt/lists/*
    


# Installa le librerie Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Imposta la cartella di lavoro
WORKDIR /app

CMD ["bash"]
