SCRIPT_FUNCTIONS = {
    "dev1": ["send_command"],
    "dev2": ["print", "skype"],
    "dev3": ["repr"],
    "dev4": ["testProxy", "proxy", "html_source"],
    "dev5": ["dns"],
    "dev6": ["scan", "exploitTest", "send"],
    "dev7": ["botnetCommand", "command"],
    "test1": ["print", "fetch", "execute"],
    "test2": ["print", "retrieve", "skype", "sql"],
    "test3": ["find", "pcap"],
    "test4": ["handle", "extract"],
    "test5": ["print", "ip", "geo"],
    "test6": ["inject", "modify", "secure_ftp_interaction"],
    "test7": ["cal"],
    "train1": ["nmap"],
    "train2": ["add"],
    "train3": ["view", "get_html"],
    "train4": ["find"],
    "train5": ["print", "get_html_a_tags", "extract"],
    "train6": ["test", "html"],
    "train7": ["connect"],
    "train8": ["print", "cookies"],
    "train9": ["print", "execute"],
    "train10": ["spoof", "send"],
    "train11": ["find", "uris"],
    "train12": ["print", "retrieve", "cookies"],
    "train13": ["google", "queryGoogleAPI"],
    "train14": ["google", "queryGoogleAPI"],
    "train15": ["google", "queryGoogleAPI"],
    "train16": ["init"],
    "train17": ["get"],
    "train18": ["find_interests", "extract"],
    "train19": ["twitter", "mentioned", "cities"],    
    "train20": ["cities", "city"],
    "train21": ["twitter_locate", "mentioned", "cities"],
    "train22": ["get", "tweet"],
    "train23": ["__init__"],
    "train24": ["_repr"],
    "train25": ["get_social"],
    "train26": ["query", "fetch_tweets", "social_media"],
    "train27": ["send", "email", "skype_messages"],
    "train28": ["__init__"],
    "train29": ["send_command"],    
    "train30": ["exploit", "syn_flood_attack", "send"],
    "train31": ["smb"],
    "train32": ["setup", "write"],
    "train33": ["_init", "_connect"],
    "train34": ["syn"],
    "train35": ["print", "query"],
    "train36": ["testForExif", "exif"],
    "train37": ["returnDefault", "default"],
    "train38": ["Table", "message"],
    "train39": ["find", "update_dependencies", "pcap", "packets"],    
    "train41": ["mirror", "images"],
    "train42": ["brute"],
    "train43": ["retKML", "kml"],
    "train44": ["connect"],
    "train45": ["find", "tags"],
    "train46": ["download"],
    "train47": ["print", "google_urls"],
    "train48": ["print", "skype_messages"],
    "train49": ["anon"],    
    "train50": ["conn", "send"],
    "train51": ["command"],
    "train52": ["print", "messages", "message", "msgDB"],
    "train53": ["connect"],
    "train54": ["print", "_extract"],
    "train55": ["testTTL", "_ttl", "extractPacketInfo"],
    "train56": ["retGeoStr", "geo"],
    "train57": ["conficker", "config_file"],
    "train58": ["connect"]
}

SCRIPT_CLASSES = {
    "dev3": "Book",
    "train7": "SSHTester",
    "train16": "TweetClient",
    "train17": "TweetClient",
    "train18": "TweetClient",
    "train19": "TweetClient",
    "train23": "Persona",    
    "train24": "Persona",
    "train25": "Persona",
    "train26": "TweetClient",
    "train28": "WebPage",
    "train33": "SecureConnection",
    "train51": "SSHTester"
}
