[[testcases]]
src = "192.168.99.20"
dst = "192.168.99.2"
iface = "eth0"
count = 1

[[testcases]]
src = "0.0.0.0"
dst = "255.255.255.255"
iface = "lo"
count = 0

[[testcases]]
src = "invalid_ip"
dst = "bad_dst"
iface = ""
count = -1
