VALID_BY_SCRIPT = {
        "dev1": ["echo", "Hello for test"],
        "dev2": ["John Doe", "john_doe", "New York", "USA", "2021-07-01 00:00:00"],
        "dev3": ["Vittime innocenti"],
        "dev4": ["<h1>Herman Melville - Moby-Dick</h1>"],
        "dev5": ["True"],
        "dev6": ["Pacchetti inviati con successo!"],
        "dev7": ["bot", "9999", "Hello for test"],
        "test1": ["John Doe", "john_doe", "New York", "USA", "1234567890", "1980-01-01", "Alice Smith", "alice", "London", "UK", "0987654321", "1990-02-02"],
        "test2": ["2021-07-01 00:00:00", "john_doe"],
        "test3": ["!lazor"],
        "test4" : ["www.example.com", "93.184.216.34"],
        "test5": ["-93", "44"],
        "test6": ["modificato"],      
        "test7": [""],        
        "train1": ["open"],
        "train2": ["127.0.0.1", "testuser", "abc123"],
        "train3": ["<h1>Benvenuto nel Test Site</h1>"],
        "train4": ["172.42.0.2", "172.42.0.3"],
        "train5": ['<a href="http://testsite.local/page1">Page 1</a>', '<a href="http://testsite.local/page2">Page 2</a>'],
        "train6": ["Your User-Agent is: Mozilla/5.0 (Windows NT 10.0; Win64; x64)"],
        "train7": ["command: /usr/bin/ssh"],
        "train8": ["Hello from Docker", "cookie_value1", "cookie_value2"],
        "train9": ["2021-07-01 00:00:00", "2021-07-02 00:00:00", "2021-07-03 00:00:00", "2021-07-04 00:00:00", "example.com", "google.com", "openai.com"],
        "train10": ["Pacchetti inviati con successo!"],
        "train11": ["/loic.zip"],
        "train12": ["example.com", "abc123", "sessionid", "prefs", "google.com", "xyz456"],
        "train13": ["Understanding A1C Test | ADA"],
        "train14": ['"title": "Google Custom Search - test"', '"searchTerms": "test"', '"cx": "93576549cfa404db2"'],
        "train15": ['"title": "Google Custom Search - test"'],
        "train16": ["test_user: ['Just had a great workout! #fitness', 'Enjoying the beautiful weather today. #sunnyday'"],       
        "train17": ["This is a mock tweet about testing.", "Nothing to do with the test word."],
        "train18": ["http://visitroma.it", "https://designer.mocky.io/", "https://example.com", "https://example.org/", "https://jsonplaceholder.typicode.com", "fashionista", "napoli_fan", "Firenze", "Milano", "Moda", "Napoli", "Roma", "Sole", "Venezia", "Viaggi"],
        "train19": ["I love walking in Rome!", "New York is beautiful in spring.", "Just got back from Milan", "Nothing beats the pizza in Naples!"],    
        "train20": ["rome", "milan", "paris", "naples", "new york"],      
        "train21": ["'Rome': None","'Milan': {'lat': 45.4642, 'lon': 9.19}", "'Paris': None", "'Naples': None"],
        "train22": ["test_user", "geo': None", "This is a mock tweet about testing", "'geo': {'lat': 37.7749, 'lon': -122.4194}", "Nothing to do with the test word."],
        "train23": ["Alice Rossi - Engineer - {'twitter': '@alice_rossi', 'linkedin': 'alice-rossi"],
        "train24": ["Alice Rossi", "Engineer"],
        "train25": ["@alice_rossi"],
        "train26": ["Enjoying the sunshine in Milan! #travel #sunny", "example_user"],
        "train27": ["sent successfully"],
        "train28": ["Example Page - This is some content. - http://example.com"],
        "train29": ["echo", "Hello for test"],    
        "train30": ["Pacchetti inviati con successo!"],
        "train31": ["set LPORT 4444"], 
        "train32": ["setg DisablePayloadHandler 1"],
        "train33": ["Establishing connection to", "localhost", "testuser", "abc123"],
        "train34": ["Pacchetti inviati con successo!"],
        "train35": ["file1.zip", "http://example.com/file1.zip", "2021-07-01 00:00:00", "file2.zip", "http://example.com/file2.zip", "2021-07-02 00:00:00"],
        "train36": ["1: 'N', 2: (60.0, 59.0, 28.97), 3: 'E', 4: (24.0, 25.0, 27.09), 7: (18.0, 28.0, 47.0), 16: 'M', 17: 178.0, 29: '2021:07:29'"],
        "train37": ["contact.asp", "home.php", "index.htm"],
        "train38": ["True"],
        "train39": ["127.0.0.1", "18"],    
        "train41": ["Immagini scaricate"],     
        "train42": ["testuser", "testpass"],
        "train43": ["128.101.101.101", "Placemark"],
        "train44": ["Connected", "Connection", "successful"],
        "train45": ["/_img/2025.01/iana-logo-header.svg"],
        "train46": ["w3schools_green.jpg", "downloaded_image.jpg"],
        "train47": ["example query", "2021-07-02 00:00:00", "openai query", "2021-07-04 00:00:00", "oexample query", "2021-07-02 00:00:00", "oopenai query", "2021-07-04 00:00:00"],
        "train48": ["To john_doe", "Hello", "How are you?"],
        "train49": ["True"],    
        "train50": ["ViolentPython", "9999"],
        "train51": ["Hello"],
        "train52": ["2021-07-01 00:00:00", "1234567890", "Hello", "2021-07-02 00:00:00", "0987654321", "How are you?"],
        "train53": ["Connection Successful", "Connected to ssh-container"],
        "train54": ["10.0.0.1", "10.0.0.11", "10.0.0.2", "10.0.0.12", "10.0.0.3", "10.0.0.13", "10.0.0.4", "10.0.0.14", "10.0.0.5", "10.0.0.15", "172.16.0.1", "172.16.0.11", "172.16.0.2", "172.16.0.12", "172.16.0.3", "172.16.0.13", "192.168.100.1", "192.168.100.11", "192.168.100.2", "192.168.100.12", "192.168.1.2", "192.168.1.3"],
        "train55": ["192.168.1.100", "64"],
        "train56": ["Frankfurt"],
        "train57": ["set LPORT 4444"],
        "train58": ["successfully", "Connection established", "Connection successful", "Connected"]
    }

EDGE_BY_SCRIPT = {
        "dev1": ["Invalid", "unset PROMPT_COMMAND"],
        "dev2": ["Error"],
        "dev3": [""],
        "dev4": ["can't fetch relative reference", "Error", "URL and proxy cannot be empty", "Invalid URL"],
        "dev5": ["False"],
        "dev6": ["Pacchetti non ricevuti"],
        "dev7": ["Error", "No output", "bot", "9999", "can only concatenate str", "None"],
        "test1": ["Error", "no such table"],
        "test2": ["Error"],
        "test3": [""],
        "test4" : ["Error"],
        "test5": ["Error"],
        "test6": [""],      
        "test7": [""],
        "train1": ["Error", "filtered", "unknown", "information is not available", "not responding", "255.255.255.255"],
        "train2": ["No client added", "root", "Error"],
        "train3": ["return window.google&&"],
        "train4": ["Error"],
        "train5": [""],
        "train6": ["<html><body><h1>Your User-Agent is: </h1></body></html>", "Error"],
        "train7": ["SSH connection failed", "Error", "Could not establish connection"],
        "train8": ["Error"],
        "train9": ["Error", "no such table:"],
        "train10": ["Error"],
        "train11": [""],
        "train12": ["Error", "no such table:"],
        "train13": [""],       
        "train14": ["Error"],
        "train15": ["Error"],
        "train16": ["Error"],       
        "train17": ["Error"],
        "train18": ["Error"],
        "train19": [""],    
        "train20": [""],      
        "train21": ["Error"],
        "train22": ["Error"],
        "train23": ["-  - {}", "Error"],
        "train24": ["Error"],
        "train25": ["Error", "Media not found"],
        "train26": ["Error"],
        "train27": ["Error", "failed"],
        "train28": ["-  -", "Error"],
        "train29": [""],    
        "train30": ["Pacchetti non inviati", "Error"],
        "train31": ["Error"], 
        "train32": ["Error"],
        "train33": ["Error"],
        "train34": ["Pacchetti non ricevuti", "Error"],
        "train35": ["Error"],
        "train36": ["No Exif data found"],
        "train37": [""],
        "train38": ["False", "Error"],
        "train39": ["192.168.0.100", "2", "10.0.0.2", "3"],    
        "train41": ["Error"],        
        "train42": [""],
        "train43": ["Placemark"],
        "train44": ["Error", "failed", "Invalid input", "Exception"],
        "train45": ["portal/wikipedia.org/assets/img/Wikipedia-logo-v2.png"],
        "train46": ["'NoneType' object is not subscriptable", "Error"],
        "train47": ["Error"],
        "train48": ["Error"],
        "train49": ["False", "Error", "Errno"],    
        "train50": ["80/tcp closed", "Error"],
        "train51": ["Error"],
        "train52": ["Error"],
        "train53": ["Error"],
        "train54": [""],
        "train55": ["10.0.0.5", "128"],
        "train56": ["Brisbane", "AU", "Unregistered"],
        "train57": ["Error"],
        "train58": ["Error", "failed", "Invalid input", "Exception"]
    }

INVALID_BY_SCRIPT = {
        "dev1": ["'int' object has no attribute 'encode'", "unset PROMPT_COMMAND", "Invalid", "Error", "must be"],
        "dev2": ["Error"],
        "dev3": ["123", "Error"],
        "dev4": ["Error", "expected string or bytes-like object, got 'int'", "URL and proxy cannot be empty", "Invalid URL", "URL must be a string and proxy must be a dictionary"],
        "dev5": ["Error"],
        "dev6": ["Error"],
        "dev7": ["Error", "'int' object has no attribute 'encode'"],
        "test1": ["Error"],
        "test2": ["Error"],
        "test3": ["Error"],
        "test4" : ["Error"],
        "test5": ["Error"],
        "test6": [""],      
        "test7": ["Error"],        
        "train1": ["Error", "Invalid IP", "invalid_host"],
        "train2": ["No client added", "Error"],
        "train3": ["Error", "Invalid URL"],
        "train4": ["Error"],
        "train5": ["Error", "Invalid URL"],
        "train6": ["Error", "Invalid URL"],
        "train7": ["SSH connection failed", "Error", "Could not establish connection"],
        "train8": ["Error"],
        "train9": ["Error", "expected str, bytes or os.PathLike object"],
        "train10": ["Error"],
        "train11": ["Error"],
        "train12": ["Error", "expected str"],
        "train13": ["400", "Search term is required", "Error", "Search term must be", "Invalid search term"], 
        "train14": ["Error"],
        "train15": ["Error"],
        "train16": ["特殊字: ['Just had a great workout! #fitness', 'Enjoying the beautiful weather today. #sunnyday'"],       
        "train17": ["Error"],
        "train18": ["http://visitroma.it", "https://designer.mocky.io/", "https://example.com", "https://example.org/", "https://jsonplaceholder.typicode.com", "fashionista", "napoli_fan", "Firenze", "Milano", "Moda", "Napoli", "Roma", "Sole", "Venezia", "Viaggi"],
        "train19": ["Error"],    
        "train20": ["123456", "!!!@@@", "null", "🐱"],      
        "train21": ["Error"],
        "train22": ["Error"],
        "train23": ["名 字 - 開発者 - {'github': 'github.com/testuser"],
        "train24": ["名 字", "開発者"],
        "train25": ["github.com/testuser"],
        "train26": ["Error"],
        "train27": ["Error", "failed"],
        "train28": ["特殊ページ - 特殊文字テスト - https://テスト.jp", "Error"],
        "train29": ["not found", "Error"],    
        "train30": ["Error"],
        "train31": ["Error"], 
        "train32": ["Error"],
        "train33": ["Establishing connection to", "テストホスト"],
        "train34": ["Error"],
        "train35": ["Error"],
        "train36": ["Error"],
        "train37": ["'NoneType' object has no attribute 'sendall'", "Failed", "Error"],
        "train38": ["Error"],
        "train39": ["Error"],    
        "train41": ["Error"],       
        "train42": ["Error"],
        "train43": ["Error"],
        "train44": ["Error", "failed", "Exception"],
        "train45": ["Error"],
        "train46": ["'NoneType' object is not subscriptable", "Error"],
        "train47": ["Error"],
        "train48": ["Error"],
        "train49": ["False", "Error", "Errno"],    
        "train50": ["-1/tcp closed", "Error"],
        "train51": ["Error"],
        "train52": ["Error"],
        "train53": ["Error", "Exception"],
        "train54": ["Error"],
        "train55": ["Error"],
        "train56": ["Unregistered", "Error", "Invalid IP address"],
        "train57": ["Error"],
        "train58": ["Error", "failed", "Exception"]
    }
