FROM ubuntu:20.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y vsftpd && \
    mkdir -p /var/ftp/pub && \
    mkdir -p /var/run/vsftpd/empty && \
    chmod 755 /var/ftp && \
    echo "Benvenuto anonimo!" > /var/ftp/pub/info.txt

COPY vsftpd.conf /etc/vsftpd.conf

EXPOSE 21

CMD ["/usr/sbin/vsftpd", "/etc/vsftpd.conf"]
