listen=YES
anonymous_enable=YES
local_enable=NO
write_enable=NO
anon_root=/var/ftp
anon_other_write_enable=NO
anon_upload_enable=NO
anon_mkdir_write_enable=NO
dirmessage_enable=NO
xferlog_enable=YES
connect_from_port_20=YES
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
listen_ipv6=NO
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
